const foodItem = [
  {
    id: 1,
    name: "LA Boudin Egg Rolls (3)",
    category: "appetizers",
    rating: 4.3,
    price: 10.0,
    img: "images/hamburger.jpg",
    quantity: 1,
    desc: "This Is the description",
  },
  {
    id: 2,
    name: "Avin's Drop Shot Tater Tots",
    category: "appetizers",
    rating: 4.3,
    price: 10.0,
    img: "#",
    quantity: 1,
    desc: "This Is the description",
  },
  {
    id: 3,
    name: "Drunken Onions",
    category: "appetizers",
    rating: 4.3,
    price: 8.0,
    img: "#",
    quantity: 1,
    desc: "This Is the description",
  },
  {
    id: 4,
    name: "Touchdown Platter",
    category: "appetizers",
    rating: 4.3,
    price: 18.0,
    img: "#",
    quantity: 1,
    desc: "This Is the description",
  },
  {
    id: 5,
    name: "At the Downs Nachos",
    category: "appetizers",
    rating: 4.3,
    price: 14.0,
    img: "#",
    quantity: 1,
  },
  {
    id: 6,
    name: "Chips & Salsa",
    category: "appetizers",
    rating: 4.3,
    price: 8.0,
    img: "#",
    quantity: 1,
  },
  {
    id: 7,
    name: "Super Bowl Salad",
    category: "salad",
    rating: 4.3,
    price: 13.0,
    img: "#",
    quantity: 1,
  },
  {
    id: 8,
    name: "Caesar Salad",
    category: "salad",
    rating: 4.3,
    price: 10.0,
    img: "#",
    quantity: 1,
  },
  {
    id: 9,
    name: "Chicken & Sausage Gumbo",
    category: "soup",
    rating: 4.3,
    price: 8.0,
    img: "#",
    quantity: 1,
  },
  {
    id: 9,
    name: "Win (6 wings)",
    category: "lineup",
    rating: 4.3,
    price: 6.0,
    img: "#",
    quantity: 1,
  },
  {
    id: 10,
    name: "Place (12 wings)",
    category: "lineup",
    rating: 4.3,
    price: 11.0,
    img: "#",
    quantity: 1,
  },
  {
    id: 11,
    name: "Win (20 wings)",
    category: "lineup",
    rating: 4.3,
    price: 22.0,
    img: "#",
    quantity: 1,
  },
  {
    id: 12,
    name: "KP's Ribeye Steak",
    category: "entrees",
    rating: 4.3,
    price: 22.0,
    img: "#",
    quantity: 1,
  },
  {
    id: 13,
    name: "Tom's Timeout Seafood Platter",
    category: "entrees",
    rating: 4.3,
    price: 23.0,
    img: "#",
    quantity: 1,
  },
  {
    id: 14,
    name: "Shrimp",
    category: "poBoys",
    rating: 4.3,
    price: 16.0,
    img: "#",
    quantity: 1,
  },
  {
    id: 15,
    name: "Catfish",
    category: "poBoys",
    rating: 4.3,
    price: 15.0,
    img: "#",
    quantity: 1,
  },
  {
    id: 16,
    name: "Pimento Cheeseburger",
    category: "burger",
    rating: 4.3,
    price: 13.0,
    img: "#",
    quantity: 1,
  },
  {
    id: 17,
    name: "Grilled Chicken Sandwich",
    category: "burger",
    rating: 4.3,
    price: 13.0,
    img: "#",
    quantity: 1,
  },
  {
    id: 18,
    name: "Inside Rail Grand Slam",
    category: "burger",
    rating: 4.3,
    price: 16.0,
    img: "#",
    quantity: 1,
  },
  {
    id: 19,
    name: "Philly Cheeesesteak",
    category: "burger",
    rating: 4.3,
    price: 14.0,
    img: "#",
    quantity: 1,
  },
  {
    id: 20,
    name: "Chocolate Delight",
    category: "dessert",
    rating: 4.3,
    price: 10.0,
    img: "#",
    quantity: 1,
  },
  {
    id: 21,
    name: "Homemade Bread Pudding",
    category: "dessert",
    rating: 4.3,
    price: 10.0,
    img: "#",
    quantity: 1,
  },
  {
    id: 22,
    name: "Tea",
    category: "drink",
    rating: 4.3,
    price: 10.0,
    img: "#",
    quantity: 1,
  },
];

export { foodItem };
